name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: fuegofro/pitch-pipe-web/.github/workflows/_deploy-impl.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
